#! /bin/sh

$HOME/.config/polybar/launch.sh

xsetroot -cursor_name left_ptr &

sxhkd & 
picom &
dunst &
/usr/lib/geoclue-2.0/demos/agent & 
redshift-gtk &
discord &
brave &
LD_PRELOAD=/usr/lib/spotify-adblock.so spotify & 
telegram-desktop & 
wal -s -i ~/Stuff/Wallpapers/

cpupower-gui -p
#pacmd load-module module-alsa-source device=hw:0,1,0

. "${HOME}/.cache/wal/colors.sh"

bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"
bspc config presel_feedback_color "$color1"

xinput set-prop 18 309 1
xinput set-prop 18 289 1

bspc monitor -d term code browser music telegram discord spotify

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config ignore_ewmh_fullscreen all
bspc config ignore_ewmh_focus true

bspc config pointer_modifier mod1
bspc config pointer_action1 resize_side
bspc config pointer_action1 resize_corner
bspc config pointer_action3 move

wmctrl -r Spotify -t 6

bspc config external_rules_command "$HOME/.config/bspwm/scripts/spotify.sh"
bspc rule -a discord desktop=discord follow=off
bspc rule -a Pavucontrol state=floating center=on
bspc rule -a mpv state=floating center=on
bspc rule -a Vivaldi-stable desktop=browser follow=off
bspc rule -a firefox desktop=browser follow=off
bspc rule -a google-chrome desktop=browser follow=off
bspc rule -a Brave-browser desktop=browser follow=off
bspc rule -a REAPER desktop=music follow=off
bspc rule -a Cadence state=floating center=on
bspc rule -a TelegramDesktop desktop=telegram follow=off
